apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: clo835-mysql-replicaset
spec:
  replicas: 1  # Assuming only one replica for MySQL
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql-container
          image: 257315592381.dkr.ecr.us-east-1.amazonaws.com/nmbhatt-repo:db_v0.1
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "pw"
