apiVersion: v1
kind: Pod
metadata:
  name: clo835-mysql
  #namespace: database
  labels:
    app: mysql-app
spec:
  containers:
    - name: mysql-container
      image: 257315592381.dkr.ecr.us-east-1.amazonaws.com/nmbhatt-repo:db_v0.1
      ports:
        - containerPort: 3306
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: "pw"
