apiVersion: v1
kind: Service
metadata:
  name: clo-835-webapp-service
spec:
  selector:
    app: employees
    #app-type: employees
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000
  type: NodePort
  #externalTrafficPolicy: Cluster
